### ISSUE TITLE
chrome extension for displaying related issues inline

### ISSUE THREAD

**Issue by danielroe** [danielroe/unsight.dev#4]

**Comment by nickytonline** [comment]
Since this is essentially a separate project from the main project @danielroe, can I create a pnpm workspace in this project for the browser extension? For the time being, I'm working off a project on my own account just to get things moving.

**Comment by danielroe** [comment]
totally up to you! I'm happy with converting this to a workspace

or if you prefer keeping it in a separate repo in your account that's fine too!

**Comment by nickytonline** [comment]
I think it makes sense to make it a monorepo. I can set that up as part of my PR.

Also, small progress, but I'll work more on this early next week. I've worked on the Refined GitHub browser extension and they run into this issue occasionally as well, but sometimes part of the browser extension breaks because the GitHub UI gets updated. It's just a fact of lige 

That's a long way of me saying I mount the Vue app in the browser extension just after the issue header. Happy to move it elsewhere, but I think it makes more sense at the top because if there are a lot of comments, it would mean scrolling all the way down to see if there were similar issues.

I've uses a `<details />` element for the time being, but it could also just be a non-collapsible list. There's a bit of content layout shift as we're injecting our stuff client-side.

![CleanShot 2024-12-14 at 23 43 40](https://github.com/user-attachments/assets/82e98b42-3977-4bf0-b78b-7a9212e9d3a6)

Progress is here atm, https://github.com/nickytonline/unsightdotdev-webext, until I create a monorepo branch.

**Comment by danielroe** [comment]
this is pretty exciting!

I also (locally) have a duplicates endpoint which seems to be very good at actually detecting dupes
